### ISSUE TITLE
Can't find the item data using name search.

### ISSUE THREAD

**Issue by linsmod** [DiabloTools/Diablo4Tools-Releases#1]
![image](https://github.com/user-attachments/assets/c73ef79c-facf-4041-a3cb-e664e282533e)

I searched the item name but not found in files of https://github.com/DiabloTools/d4data, you know why?

**Comment by linsmod** [comment]
Oh, addition, I found something, but it incompleted. only a name and text description, where I can find it numberic value properties?
![image](https://github.com/user-attachments/assets/8860d431-4b93-473f-b29d-8a28593d8d3f)

**Comment by DiabloTools** [comment]
If you want to find the data related to the names you found you have to look into the base/meta directory for files having the same name while the first part of the name is the subdirectory (SNOGroup).
E.g. for the names found in [enUS_Text/meta/StringList/Item_Quarterstaff_Unique_Spiritborn_016_x1.stl.json](https://github.com/DiabloTools/d4data/blob/master/json/enUS_Text/meta/StringList/Item_Quarterstaff_Unique_Spiritborn_016_x1.stl.json) you have to look into [base/meta/Item/Quarterstaff_Unique_Spiritborn_016_x1.itm.json](https://github.com/DiabloTools/d4data/blob/master/json/base/meta/Item/Quarterstaff_Unique_Spiritborn_016_x1.itm.json)

Similarly the data for [enUS_Text/meta/StringList/Affix_Quarterstaff_Unique_Spiritborn_016_x1.stl.json](https://github.com/DiabloTools/d4data/blob/master/json/enUS_Text/meta/StringList/Affix_Quarterstaff_Unique_Spiritborn_016_x1.stl.json) can be found in [base/meta/Affix/Quarterstaff_Unique_Spiritborn_016_x1.aff.json](https://github.com/DiabloTools/d4data/blob/master/json/base/meta/Affix/Quarterstaff_Unique_Spiritborn_016_x1.aff.json)

**Comment by linsmod** [comment]
Oh thank you, BTW. does compiled means encrypted? Can i get the decrypted value?
![image](https://github.com/user-attachments/assets/4168c06e-d2a7-4022-967a-5c8510c47b90)

**Comment by DiabloTools** [comment]
`compiled` is just the binary representation of the field `value` Blizzard uses for formulas encoded as base64.
